// Code generated by hertz generator.

package user

import (
	"LearnShare/biz/router/auth"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logininMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginoutMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _refreshtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadavatarMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _meMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateemailMw() []app.HandlerFunc {
	return auth.Auth()
}

func _updatemajorMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _passwordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepasswordMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _resetpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _emailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendverifyemailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _verifyemailMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _adminMw() []app.HandlerFunc {
	// 管理员路由组，需要认证
	return auth.Auth()
}

func _getpermissionlistMw() []app.HandlerFunc {
	// 获取权限列表，需要 role.manage 权限
	return []app.HandlerFunc{auth.RequirePermission("role.manage")}
}

func _getrolelistMw() []app.HandlerFunc {
	// 获取角色列表，需要 role.manage 权限
	return []app.HandlerFunc{auth.RequirePermission("role.manage")}
}

func _addroleMw() []app.HandlerFunc {
	// 添加角色，需要 role.manage 权限
	return []app.HandlerFunc{auth.RequirePermission("role.manage")}
}

func _adminadduserMw() []app.HandlerFunc {
	// 管理员添加用户，需要 user.account.manage 权限
	return []app.HandlerFunc{auth.RequirePermission("user.account.manage")}
}

func _adminupdateuserMw() []app.HandlerFunc {
	// 管理员更新用户，需要 user.account.manage 权限
	return []app.HandlerFunc{auth.RequirePermission("user.account.manage")}
}
