// Code generated by hertz generator.

package user

import (
	"LearnShare/biz/router/auth"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logininMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadavatarMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _meMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateemailMw() []app.HandlerFunc {
	return auth.Auth()
}

func _updatemajorMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _passwordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepasswordMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _resetpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _emailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendverifyemailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _verifyemailMw() []app.HandlerFunc {
	// your code...
	return nil
}
