// Code generated by hertz generator.

package audit

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _auditMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcommentauditlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _auditcommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _coursesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcourseauditlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _auditcourseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resourcesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getresourceauditlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _auditresourceMw() []app.HandlerFunc {
	// your code...
	return nil
}
