// Code generated by hertz generator.

package main

import (
	"LearnShare/biz/dal"
	"LearnShare/biz/middleware"
	"LearnShare/config"
	"github.com/cloudwego/hertz/pkg/app/server"
	"log"
)

func Init() {
	config.Init()
	err := dal.Init()
	if err != nil {
		log.Fatal(err)
	}
	middleware.Init()
}

func main() {
	Init()
	h := server.Default()

	register(h)
	h.Spin()
}
