// Code generated by hertz generator.

package main

import (
	"time"

	"LearnShare/biz/dal"
	"LearnShare/biz/middleware"
	"LearnShare/config"
	"LearnShare/pkg/logger"
	"LearnShare/pkg/utils"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/pprof"
)

func Init() {
	config.Init()

	// 初始化日志系统（传递环境参数）
	if err := logger.Init(config.Logger.Dir, config.Logger.Level, config.Logger.Env); err != nil {
		logger.Fatalf("日志系统初始化失败: %v", err)
	}
	logger.Infof("日志系统初始化成功 | env=%s level=%s", config.Logger.Env, config.Logger.Level)

	err := dal.Init()
	if err != nil {
		logger.Fatalf("数据库初始化失败: %v", err)
	}
	middleware.InitJWT()
}

func main() {
	Init()
	h := server.Default(server.WithHostPorts(utils.GetServerAddress()))

	// 添加请求日志中间件
	h.Use(middleware.RequestLogger())

	// 添加慢查询监控中间件（阈值 1000ms）
	h.Use(middleware.SlowQueryLogger(1000))

	if config.Cors == nil {
		logger.Warnf("CORS 配置缺失，跳过跨域拦截器注册")
	} else {
		h.Use(cors.New(cors.Config{
			AllowOrigins:  config.Cors.AllowOrigins,
			AllowMethods:  config.Cors.AllowMethods,
			AllowHeaders:  config.Cors.AllowHeaders,
			ExposeHeaders: config.Cors.ExposeHeaders,
			MaxAge:        time.Duration(config.Cors.MaxAge) * time.Second,
			AllowWildcard: config.Cors.AllowWildcard,
		}))
	}

	// 注册 pprof 性能分析路由
	pprof.Register(h)

	register(h)
	logger.Infof("服务器启动成功 | 监听地址=%s", utils.GetServerAddress())
	h.Spin()
}
