// Code generated by hertz generator.

package main

import (
	"LearnShare/biz/dal"
	"LearnShare/biz/middleware"
	"LearnShare/config"
	"LearnShare/pkg/utils"
	"log"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/pprof"
)

func Init() {
	config.Init()
	err := dal.Init()
	if err != nil {
		log.Fatal(err)
	}
	middleware.InitJWT()
}

func main() {
	Init()
	h := server.Default(server.WithHostPorts(utils.GetServerAddress()))

	// 注册 pprof 性能分析路由
	pprof.Register(h)

	register(h)
	h.Spin()
}
