// Code generated by hertz generator.

package school_struct

import (
	"LearnShare/biz/pack"
	"context"

	school_struct "LearnShare/biz/model/school_struct"

	"github.com/cloudwego/hertz/pkg/app"
)

// AdminAddCollege .
// @router /api/admin/colleges [POST]
func AdminAddCollege(ctx context.Context, c *app.RequestContext) {
	var err error
	var req school_struct.AdminAddCollegeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(school_struct.AdminAddCollegeResp)

	pack.SendResponse(c, resp)
}

// AdminAddMajor .
// @router /api/admin/majors [POST]
func AdminAddMajor(ctx context.Context, c *app.RequestContext) {
	var err error
	var req school_struct.AdminAddMajorReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(school_struct.AdminAddMajorResp)

	pack.SendResponse(c, resp)
}

// AdminAddTeacher .
// @router /api/admin/teachers [POST]
func AdminAddTeacher(ctx context.Context, c *app.RequestContext) {
	var err error
	var req school_struct.AdminAddTeacherReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(school_struct.AdminAddTeacherResp)

	pack.SendResponse(c, resp)
}
