// Code generated by hertz generator.

package school_struct

import (
	"LearnShare/biz/pack"
	"LearnShare/biz/service"
	"LearnShare/pkg/errno"
	"context"

	"LearnShare/biz/model/school_struct"

	"github.com/cloudwego/hertz/pkg/app"
)

// AdminAddCollege .
// @router /api/admin/colleges [POST]
func AdminAddCollege(ctx context.Context, c *app.RequestContext) {
	var err error
	var req school_struct.AdminAddCollegeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(school_struct.AdminAddCollegeResp)

	// 调用服务层
	collegeID, err := service.NewSchoolStructService(ctx, c).AdminAddCollege(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	resp.CollegeID = collegeID

	pack.SendResponse(c, resp)
}

// AdminAddMajor .
// @router /api/admin/majors [POST]
func AdminAddMajor(ctx context.Context, c *app.RequestContext) {
	var err error
	var req school_struct.AdminAddMajorReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(school_struct.AdminAddMajorResp)

	// 调用服务层
	majorID, err := service.NewSchoolStructService(ctx, c).AdminAddMajor(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	resp.MajorID = majorID

	pack.SendResponse(c, resp)
}

// AdminAddTeacher .
// @router /api/admin/teachers [POST]
func AdminAddTeacher(ctx context.Context, c *app.RequestContext) {
	var err error
	var req school_struct.AdminAddTeacherReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(school_struct.AdminAddTeacherResp)

	// 调用服务层
	teacherID, err := service.NewSchoolStructService(ctx, c).AdminAddTeacher(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	resp.TeacherID = teacherID

	pack.SendResponse(c, resp)
}
