// Code generated by hertz generator.

package school_struct

import (
	"LearnShare/biz/pack"
	"context"

	school_struct "LearnShare/biz/model/school_struct"

	"github.com/cloudwego/hertz/pkg/app"
)

// GetCollegeList .
// @router /school/college/list [GET]
func GetCollegeList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req school_struct.GetCollegeListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(school_struct.GetCollegeListResp)

	pack.SendResponse(c, resp)
}

// GetMajorList .
// @router /school/major/list [GET]
func GetMajorList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req school_struct.GetMajorListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(school_struct.GetMajorListResp)

	pack.SendResponse(c, resp)
}

// GetTeacherList .
// @router /school/teacher/list [GET]
func GetTeacherList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req school_struct.GetTeacherListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(school_struct.GetTeacherListResp)

	pack.SendResponse(c, resp)
}
