// Code generated by hertz generator.

package school_struct

import (
	"LearnShare/biz/pack"
	"LearnShare/biz/service"
	"context"

	"LearnShare/biz/model/school_struct"

	"github.com/cloudwego/hertz/pkg/app"
)

// GetCollegeList .
// @router /school/college/list [GET]
func GetCollegeList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req school_struct.GetCollegeListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// 调用服务层
	svc := service.NewSchoolStructService(ctx, c)
	colleges, total, err := svc.GetCollegeList(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := &school_struct.GetCollegeListResp{
		Total:       total,
		CollegeList: colleges,
	}

	pack.SendResponse(c, resp)
}

// GetMajorList .
// @router /school/major/list [GET]
func GetMajorList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req school_struct.GetMajorListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// 调用服务层
	svc := service.NewSchoolStructService(ctx, c)
	majors, total, err := svc.GetMajorList(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := &school_struct.GetMajorListResp{
		Total:     total,
		MajorList: majors,
	}

	pack.SendResponse(c, resp)
}

// GetTeacherList .
// @router /school/teacher/list [GET]
func GetTeacherList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req school_struct.GetTeacherListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// 调用服务层
	svc := service.NewSchoolStructService(ctx, c)
	teachers, total, err := svc.GetTeacherList(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := &school_struct.GetTeacherListResp{
		Total:       total,
		TeacherList: teachers,
	}

	pack.SendResponse(c, resp)
}
