// Code generated by hertz generator.

package resource

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resourcesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadresourceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getresourceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __7bresource_id_7dMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadresourceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reportresourceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resources0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchresourcesMw() []app.HandlerFunc {
	// your code...
	return nil
}
