// Code generated by hertz generator.

package resource

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resourcesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadresourceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getresourceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __7bresource_id_7dMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadresourceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reportresourceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resources0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchresourcesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resourceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __7bresource_id_7d0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getresourcecommentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resource_commentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitresourcecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resource_ratingsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteresourceratingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitresourceratingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resources_commentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteresourcecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}
