// Code generated by hertz generator.

package resource

import (
	"LearnShare/biz/router/auth"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resourcesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadresourceMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		auth.AccessTokenAuth(),
	}
}

func _getresourceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadresourceMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		auth.AccessTokenAuth(),
	}
}

func _reportresourceMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		auth.AccessTokenAuth(),
	}
}

func _resources0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchresourcesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resourceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getresourcecommentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resource_commentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitresourcecommentMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		auth.AccessTokenAuth(),
	}
}

func _resource_ratingsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteresourceratingMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		auth.AccessTokenAuth(),
	}
}

func _submitresourceratingMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		auth.AccessTokenAuth(),
	}
}

func _resources_commentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteresourcecommentMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		auth.AccessTokenAuth(),
	}
}

func _reportMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resources1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resource_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resource_id0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		auth.AccessTokenAuth(),
	}
}

func _admindeleteresourcecommentMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		auth.RequirePermission("resource.comment.moderate"),
	}
}

func _admindeleteresourceratingMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		auth.RequirePermission("resource.rating.moderate"),
	}
}

func _admindeleteresourceMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		auth.RequirePermission("resource.manage_all"),
	}
}

func _resource_comments0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resource_ratings0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _comment_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reactresourcecommentMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		auth.AccessTokenAuth(),
	}
}
