// Code generated by hertz generator.

package resource

import (
	"LearnShare/biz/pack"
	"context"

	resource "LearnShare/biz/model/resource"

	"github.com/cloudwego/hertz/pkg/app"
)

// AdminDeleteResourceComment .
// @router /api/admin/resource_comments/:comment_id [DELETE]
func AdminDeleteResourceComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req resource.AdminDeleteResourceCommentReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(resource.AdminDeleteResourceCommentResp)

	pack.SendResponse(c, resp)
}

// AdminDeleteResourceRating .
// @router /api/admin/resource_ratings/:rating_id [DELETE]
func AdminDeleteResourceRating(ctx context.Context, c *app.RequestContext) {
	var err error
	var req resource.AdminDeleteResourceRatingReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(resource.AdminDeleteResourceRatingResp)

	pack.SendResponse(c, resp)
}

// AdminDeleteResource .
// @router /api/admin/resources/:resource_id [DELETE]
func AdminDeleteResource(ctx context.Context, c *app.RequestContext) {
	var err error
	var req resource.AdminDeleteResourceReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(resource.AdminDeleteResourceResp)

	pack.SendResponse(c, resp)
}
