// Code generated by hertz generator.

package resource

import (
	"context"

	resource "LearnShare/biz/model/resource"
	"LearnShare/biz/pack"
	"LearnShare/biz/service"
	"LearnShare/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
)

// SearchResources .
// @router /api/resources/search [GET]
func SearchResources(ctx context.Context, c *app.RequestContext) {
	var err error
	var req resource.SearchResourceReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	if req.TagId != nil && *req.TagId == 0 {
		req.TagId = nil
	}
	if req.CourseID != nil && *req.CourseID == 0 {
		req.CourseID = nil
	}

	resp := new(resource.SearchResourceResp)

	// Call service
	moduleResources, total, err := service.NewResourceService(ctx, c).SearchResources(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// Build response
	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	resp.Resources = moduleResources
	resp.Total = int32(total)

	pack.SendResponse(c, resp)
}

// UploadResource .
// @router /api/resources [POST]
func UploadResource(ctx context.Context, c *app.RequestContext) {
	var err error
	var req resource.UploadResourceReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(resource.UploadResourceResp)
	resp.BaseResp = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}

// DownloadResource .
// @router /api/resources/{resource_id}/download [GET]
func DownloadResource(ctx context.Context, c *app.RequestContext) {
	var err error
	var req resource.DownloadResourceReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(resource.DownloadResourceResp)
	resp.BaseResp = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}

// ReportResource .
// @router /api/resources/{resource_id}/report [POST]
func ReportResource(ctx context.Context, c *app.RequestContext) {
	var err error
	var req resource.ReportResourceReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(resource.ReportResourceResp)

	// 调用服务
	err = service.NewResourceService(ctx, c).ReportResource(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// Build response
	resp.BaseResp = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}

// GetResource .
// @router /api/resources/{resource_id} [GET]
func GetResource(ctx context.Context, c *app.RequestContext) {
	var err error
	var req resource.GetResourceReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(resource.GetResourceResp)

	// Call service
	resource, err := service.NewResourceService(ctx, c).GetResource(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// Build response
	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	resp.Resource = resource

	pack.SendResponse(c, resp)
}

// SubmitResourceRating .
// @router /api/resource_ratings/{resource_id} [POST]
func SubmitResourceRating(ctx context.Context, c *app.RequestContext) {
	var err error
	var req resource.SubmitResourceRatingReq

	// 使用BindAndValidate统一绑定路径参数和请求体参数
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(resource.SubmitResourceRatingResp)

	// 调用服务
	_, err = service.NewResourceService(ctx, c).SubmitResourceRating(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.BaseResp = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}

// DeleteResourceRating .
// @router /api/resource_ratings/{rating_id} [DELETE]
func DeleteResourceRating(ctx context.Context, c *app.RequestContext) {
	var err error
	var req resource.DeleteResourceRatingReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(resource.DeleteResourceRatingResp)

	// 调用服务
	err = service.NewResourceService(ctx, c).DeleteResourceRating(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// Build response
	resp.BaseResp = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}

// SubmitResourceComment .
// @router /api/resource_comments/{resource_id} [POST]
func SubmitResourceComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req resource.SubmitResourceCommentReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(resource.SubmitResourceCommentResp)

	// Call service
	_, err = service.NewResourceService(ctx, c).SubmitResourceComment(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// Build response
	resp.BaseResp = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}

// DeleteResourceComment .
// @router /api/resource_comments/{comment_id} [DELETE]
func DeleteResourceComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req resource.DeleteResourceCommentReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(resource.DeleteResourceCommentResp)

	// 调用服务
	err = service.NewResourceService(ctx, c).DeleteResourceComment(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// Build response
	resp.BaseResp = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}

// GetResourceComments .
// @router /api/resource/{resource_id}/comment [GET]
func GetResourceComments(ctx context.Context, c *app.RequestContext) {
	var err error
	var req resource.GetResourceCommentsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(resource.GetResourceCommentsResp)

	// Call service
	comments, total, err := service.NewResourceService(ctx, c).GetResourceComments(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// Build response
	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	resp.Comments = comments
	resp.Total = int32(total)

	pack.SendResponse(c, resp)
}
