// Code generated by hertz generator.

package course

import (
	"LearnShare/biz/pack"
	"LearnShare/biz/service"
	"LearnShare/pkg/errno"
	"context"

	"LearnShare/biz/model/course"

	"github.com/cloudwego/hertz/pkg/app"
)

// AdminDeleteCourseComment .
// @router /api/admin/course_comments/:comment_id [DELETE]
func AdminDeleteCourseComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req course.AdminDeleteCourseCommentReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(course.AdminDeleteCourseCommentResp)

	// 调用 service 层逻辑
	if err = service.NewCourseService(ctx, c).AdminDeleteCourseComment(&req); err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// AdminDeleteCourseRating .
// @router /api/admin/course_ratings/:rating_id [DELETE]
func AdminDeleteCourseRating(ctx context.Context, c *app.RequestContext) {
	var err error
	var req course.AdminDeleteCourseRatingReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(course.AdminDeleteCourseRatingResp)

	// 调用 service 层逻辑
	if err = service.NewCourseService(ctx, c).AdminDeleteCourseRating(&req); err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// AdminDeleteCourse .
// @router /api/admin/courses/:course_id [DELETE]
func AdminDeleteCourse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req course.AdminDeleteCourseReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(course.AdminDeleteCourseResp)

	// 调用 service 层逻辑
	if err = service.NewCourseService(ctx, c).AdminDeleteCourse(&req); err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}
