// Code generated by hertz generator.

package course

import (
	"LearnShare/biz/pack"
	"context"

	course "LearnShare/biz/model/course"

	"github.com/cloudwego/hertz/pkg/app"
)

// AdminDeleteCourseComment .
// @router /api/admin/course_comments/:comment_id [DELETE]
func AdminDeleteCourseComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req course.AdminDeleteCourseCommentReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(course.AdminDeleteCourseCommentResp)

	pack.SendResponse(c, resp)
}

// AdminDeleteCourseRating .
// @router /api/admin/course_ratings/:rating_id [DELETE]
func AdminDeleteCourseRating(ctx context.Context, c *app.RequestContext) {
	var err error
	var req course.AdminDeleteCourseRatingReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(course.AdminDeleteCourseRatingResp)

	pack.SendResponse(c, resp)
}

// AdminDeleteCourse .
// @router /api/admin/courses/:course_id [DELETE]
func AdminDeleteCourse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req course.AdminDeleteCourseReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(course.AdminDeleteCourseResp)

	pack.SendResponse(c, resp)
}
