// Code generated by hertz generator.

package course

import (
	course "LearnShare/biz/model/course"
	"LearnShare/biz/pack"
	"LearnShare/biz/service"
	"LearnShare/pkg/errno"
	"context"

	"github.com/cloudwego/hertz/pkg/app"
)

// Search .
// @router /api/courses/search [GET]
func Search(ctx context.Context, c *app.RequestContext) {
	var err error
	var req course.SearchReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(course.SearchResp)

	// Call service
	resp, err = service.NewCourseService(ctx, c).Search(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// Build response
	resp.BaseResponse = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}

// GetCourseDetail .
// @router /api/courses/{course_id} [GET]
func GetCourseDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req course.GetCourseDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(course.GetCourseDetailResp)

	// Call service
	resp, err = service.NewCourseService(ctx, c).GetCourseDetail(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// Build response
	resp.BaseResponse = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}

// GetCourseResourceList .
// @router /api/courses/{course_id}/resources [GET]
func GetCourseResourceList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req course.GetCourseResourceListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(course.GetCourseResourceListResp)

	// Call service
	resp, err = service.NewCourseService(ctx, c).GetCourseResourceList(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// Build response
	resp.BaseResponse = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}

// GetCourseComments .
// @router /api/courses/{course_id}/comments [GET]
func GetCourseComments(ctx context.Context, c *app.RequestContext) {
	var err error
	var req course.GetCourseCommentsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(course.GetCourseCommentsResp)

	// Call service
	resp, err = service.NewCourseService(ctx, c).GetCourseComments(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// Build response
	resp.BaseResponse = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}

// SubmitCourseRating .
// @router /api/course_ratings/{course_id} [POST]
func SubmitCourseRating(ctx context.Context, c *app.RequestContext) {
	var err error
	var req course.SubmitCourseRatingReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(course.SubmitCourseRatingResp)

	// Call service
	resp, err = service.NewCourseService(ctx, c).SubmitCourseRating(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// Build response
	resp.BaseResponse = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}

// SubmitCourseComment .
// @router /api/courses/{course_id}/comments [POST]
func SubmitCourseComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req course.SubmitCourseCommentReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(course.SubmitCourseCommentResp)

	// Call service
	resp, err = service.NewCourseService(ctx, c).SubmitCourseComment(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// Build response
	resp.BaseResponse = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}

// DeleteCourseComment .
// @router /api/courses_comments/{comment_id} [DELETE]
func DeleteCourseComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req course.DeleteCourseCommentReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(course.DeleteCourseCommentResp)

	// Call service
	resp, err = service.NewCourseService(ctx, c).DeleteCourseComment(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// Build response
	resp.BaseResponse = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}

// DeleteCourseRating .
// @router /api/course_ratings/{rating_id} [DELETE]
func DeleteCourseRating(ctx context.Context, c *app.RequestContext) {
	var err error
	var req course.DeleteCourseRatingReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(course.DeleteCourseRatingResp)

	// Call service
	resp, err = service.NewCourseService(ctx, c).DeleteCourseRating(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// Build response
	resp.BaseResponse = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}