// Code generated by hertz generator.

package user

import (
	"LearnShare/biz/pack"
	"context"

	user "LearnShare/biz/model/user"

	"github.com/cloudwego/hertz/pkg/app"
)

// GetPermissionList .
// @router /api/admin/permissions [GET]
func GetPermissionList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetPermissionListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.GetPermissionListResp)

	pack.SendResponse(c, resp)
}

// GetRoleList .
// @router /api/admin/roles [GET]
func GetRoleList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetRoleListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.GetRoleListResp)

	pack.SendResponse(c, resp)
}

// AddRole .
// @router /api/admin/roles [POST]
func AddRole(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.AddRoleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.AddRoleResp)

	pack.SendResponse(c, resp)
}
