// Code generated by hertz generator.

package user

import (
	"LearnShare/biz/pack"
	"LearnShare/biz/service"
	"LearnShare/pkg/errno"
	"context"

	"LearnShare/biz/model/user"

	"github.com/cloudwego/hertz/pkg/app"
)

// GetPermissionList .
// @router /api/admin/permissions [GET]
func GetPermissionList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetPermissionListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.GetPermissionListResp)

	permissions, err := service.NewRoleAdminService(ctx, c).GetPermissionList()
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	resp.PermissionList = permissions

	pack.SendResponse(c, resp)
}

// GetRoleList .
// @router /api/admin/roles [GET]
func GetRoleList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetRoleListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.GetRoleListResp)

	roles, err := service.NewRoleAdminService(ctx, c).GetRoleList()
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	resp.RoleList = roles

	pack.SendResponse(c, resp)
}

// AddRole .
// @router /api/admin/roles [POST]
func AddRole(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.AddRoleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.AddRoleResp)

	roleID, err := service.NewRoleAdminService(ctx, c).AddRole(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	resp.RoleID = roleID

	pack.SendResponse(c, resp)
}
