// Code generated by hertz generator.

package user

import (
	"LearnShare/biz/pack"
	"context"

	user "LearnShare/biz/model/user"

	"github.com/cloudwego/hertz/pkg/app"
)

// AdminAddUser .
// @router /api/admin/users [POST]
func AdminAddUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.AdminAddUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.AdminAddUserResp)

	pack.SendResponse(c, resp)
}

// AdminUpdateUser .
// @router /api/admin/users [PUT]
func AdminUpdateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.AdminUpdateUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.AdminUpdateUserResp)

	pack.SendResponse(c, resp)
}
