// Code generated by hertz generator.

package audit

import (
	"LearnShare/biz/pack"
	"LearnShare/biz/service"
	"LearnShare/pkg/errno"
	"context"

	"LearnShare/biz/model/audit"

	"github.com/cloudwego/hertz/pkg/app"
)

// GetResourceAuditList .
// @router /api/admin/audit/resources [GET]
func GetResourceAuditList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req audit.GetResourceAuditListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(audit.GetResourceAuditListResp)
	// 调用服务
	reviews, err := service.NewAuditService(ctx, c).GetResourceAuditList(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// 构建响应
	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	resp.ResourceReviewList = reviews

	pack.SendResponse(c, resp)
}

// AuditResource .
// @router /api/admin/audit/resources/:review_id [PUT]
func AuditResource(ctx context.Context, c *app.RequestContext) {
	var err error
	var req audit.AuditResourceReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(audit.AuditResourceResp)
	// 调用服务
	err = service.NewAuditService(ctx, c).AuditResource(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	// 构建响应
	resp.BaseResp = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}

// GetCourseAuditList .
// @router /api/admin/audit/courses [GET]
func GetCourseAuditList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req audit.GetCourseAuditListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(audit.GetCourseAuditListResp)

	pack.SendResponse(c, resp)
}

// AuditCourse .
// @router /api/admin/audit/courses/:review_id [POST]
func AuditCourse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req audit.AuditCourseReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(audit.AuditCourseResp)

	pack.SendResponse(c, resp)
}

// GetCommentAuditList .
// @router /api/admin/audit/comments [GET]
func GetCommentAuditList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req audit.GetCommentAuditListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(audit.GetCommentAuditListResp)

	pack.SendResponse(c, resp)
}

// AuditCourseComment .
// @router /api/admin/audit/course_comments/:review_id [POST]
func AuditCourseComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req audit.AuditCourseCommentReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(audit.AuditCourseCommentResp)
	err = service.NewAuditService(ctx, c).AuditCourseComment(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}
	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// AuditResourceComment .
// @router /api/admin/audit/resource_comments/:review_id [POST]
func AuditResourceComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req audit.AuditResourceCommentReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(audit.AuditResourceCommentResp)
	err = service.NewAuditService(ctx, c).AuditResourceComment(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}
	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// GetCourseCommentAuditList .
// @router /api/admin/audit/course_comments [GET]
func GetCourseCommentAuditList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req audit.GetCourseCommentAuditListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(audit.GetCourseCommentAuditListResp)
	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// GetResourceCommentAuditList .
// @router /api/admin/audit/resource_comments [GET]
func GetResourceCommentAuditList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req audit.GetResourceCommentAuditListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(audit.GetResourceCommentAuditListResp)
	resp.BaseResp = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}
