// Code generated by hertz generator.

package course

import (
	"LearnShare/biz/router/auth"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _course_ratingsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecourseratingMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		auth.AccessTokenAuth(),
	}
}

func _submitcourseratingMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		auth.AccessTokenAuth(),
	}
}

func _coursesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcoursedetailMw() []app.HandlerFunc {
	// 课程详情公开访问，不需要认证
	return nil
}

func _getcoursecommentsMw() []app.HandlerFunc {
	// 获取课程评论公开访问，不需要认证
	return nil
}

func _submitcoursecommentMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		auth.AccessTokenAuth(),
	}
}

func _getcourseresourcelistMw() []app.HandlerFunc {
	// 获取课程资源列表公开访问，不需要认证
	return nil
}

func _searchMw() []app.HandlerFunc {
	// 搜索功能公开访问，不需要认证
	return nil
}

func _courses_commentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecoursecommentMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		auth.AccessTokenAuth(),
	}
}

func _course_commentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _course_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admindeletecoursecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admindeletecourseratingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admindeletecourseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _course_comments0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _course_ratings0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _courses0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _comment_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reactcoursecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}
