// Code generated by hertz generator.

package course

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _course_ratingsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecourseratingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitcourseratingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _coursesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __7bcourse_id_7dMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcoursedetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcoursecommentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitcoursecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcourseresourcelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _courses_commentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecoursecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}
