// Code generated by hertz generator.

package course

import (
	"LearnShare/biz/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _course_ratingsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecourseratingMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.AccessTokenJwtMiddleware.MiddlewareFunc(), // 删除课程评分需要认证
	}
}

func _submitcourseratingMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.AccessTokenJwtMiddleware.MiddlewareFunc(), // 提交课程评分需要认证
	}
}

func _coursesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __7bcourse_id_7dMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcoursedetailMw() []app.HandlerFunc {
	// 课程详情公开访问，不需要认证
	return nil
}

func _getcoursecommentsMw() []app.HandlerFunc {
	// 获取课程评论公开访问，不需要认证
	return nil
}

func _submitcoursecommentMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.AccessTokenJwtMiddleware.MiddlewareFunc(), // 提交课程评论需要认证
	}
}

func _getcourseresourcelistMw() []app.HandlerFunc {
	// 获取课程资源列表公开访问，不需要认证
	return nil
}

func _searchMw() []app.HandlerFunc {
	// 搜索功能公开访问，不需要认证
	return nil
}

func _courses_commentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecoursecommentMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.AccessTokenJwtMiddleware.MiddlewareFunc(), // 删除课程评论需要认证
	}
}

func _course_commentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _course_idMw() []app.HandlerFunc {
	// your code...
	return nil
}
