// Code generated by hertz generator.

package favorite

import (
	"LearnShare/biz/pack"
	"context"

	favorite "LearnShare/biz/model/favorite"

	"github.com/cloudwego/hertz/pkg/app"
)

// GetFavorites .
// @router /api/users/me/favorites [GET]
func GetFavorites(ctx context.Context, c *app.RequestContext) {
	var err error
	var req favorite.GetFavoriteReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(favorite.GetFavoriteResp)

	pack.SendResponse(c, resp)
}

// AddFavorite .
// @router /api/users/me/favorites [POST]
func AddFavorite(ctx context.Context, c *app.RequestContext) {
	var err error
	var req favorite.AddFavoriteReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(favorite.AddFavoriteResp)

	pack.SendResponse(c, resp)
}

// RemoveFavorite .
// @router /api/users/me/favorites [DELETE]
func RemoveFavorite(ctx context.Context, c *app.RequestContext) {
	var err error
	var req favorite.RemoveFavoriteReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(favorite.RemoveFavoriteResp)

	pack.SendResponse(c, resp)
}
