// Code generated by hertz generator.

package favorite

import (
	"LearnShare/biz/pack"
	"LearnShare/biz/service"
	"LearnShare/pkg/errno"
	"context"

	"LearnShare/biz/model/favorite"

	"github.com/cloudwego/hertz/pkg/app"
)

// GetFavorites .
// @router /api/users/me/favorites [GET]
func GetFavorites(ctx context.Context, c *app.RequestContext) {
	var err error
	var req favorite.GetFavoriteReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(favorite.GetFavoriteResp)

	// 调用服务层
	favorites, err := service.NewFavoriteService(ctx, c).GetFavorites(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.Resp = pack.BuildBaseResp(errno.Success)
	resp.Items = favorites

	pack.SendResponse(c, resp)
}

// AddFavorite .
// @router /api/users/me/favorites [POST]
func AddFavorite(ctx context.Context, c *app.RequestContext) {
	var err error
	var req favorite.AddFavoriteReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(favorite.AddFavoriteResp)

	// 调用服务层
	fav, err := service.NewFavoriteService(ctx, c).AddFavorite(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.Resp = pack.BuildBaseResp(errno.Success)
	resp.Favorite = fav

	pack.SendResponse(c, resp)
}

// RemoveFavorite .
// @router /api/users/me/favorites [DELETE]
func RemoveFavorite(ctx context.Context, c *app.RequestContext) {
	var err error
	var req favorite.RemoveFavoriteReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(favorite.RemoveFavoriteResp)

	// 调用服务层
	err = service.NewFavoriteService(ctx, c).RemoveFavorite(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.Resp = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}
