// Code generated by hertz generator.

package favorite

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _meMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _removefavoriteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfavoritesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addfavoriteMw() []app.HandlerFunc {
	// your code...
	return nil
}
