// Code generated by hertz generator.

package school_struct

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminaddcollegeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminaddmajorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminaddteacherMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _schoolMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _collegeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcollegelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _majorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmajorlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _teacherMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getteacherlistMw() []app.HandlerFunc {
	// your code...
	return nil
}
