// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	audit "LearnShare/biz/router/audit"
	course "LearnShare/biz/router/course"
	favorite "LearnShare/biz/router/favorite"
	module "LearnShare/biz/router/module"
	resource "LearnShare/biz/router/resource"
	school_struct "LearnShare/biz/router/school_struct"
	user "LearnShare/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	favorite.Register(r)

	audit.Register(r)

	school_struct.Register(r)

	course.Register(r)

	resource.Register(r)

	user.Register(r)

	module.Register(r)

}
