// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	course "LearnShare/biz/router/course"
	module "LearnShare/biz/router/module"
	resource "LearnShare/biz/router/resource"
	user "LearnShare/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	course.Register(r)

	resource.Register(r)

	user.Register(r)

	module.Register(r)

}
